### ISSUE TITLE
Does PyVST support midi?

### ISSUE THREAD

**Issue by inhahe** [mbrucher/PyVST#5]
I loaded a plugin called Synth1V113beta3 in JUCE's Plugin Host, and it showed that the plugin has one midi input. I even connected it to the virtual keyboard and played some notes. But when I load it with PyVST's display.py, dump_effect_properties doesn't say anything about midi inputs. Does PyVST support midi? If not, could you add it? Thanks!

**Comment by mbrucher** [comment]
As I've said, I'm not working on the project anymore.
MIDI was not something I worried about 10 years ago.
